#!/bin/bash
set -o nounset -o errexit -o pipefail

cd "$(dirname "$0")"
if test -e .git
then
  echo "This directory is not a subtree."
  exit 1
fi
repos=$(cat repos)
toplevel="$(git rev-parse --show-toplevel)"
prefix=${PWD##$toplevel/}
cd "$toplevel"
git subtree pull --prefix "$prefix" "$repos" --squash main
