#!/bin/bash
set -o nounset -o errexit -o pipefail

cd "$(dirname "$0")"
if test -e .git
then
  echo "This directory is not a subtree."
  exit 1
fi
base="$(basename "$0")"
action=
case "$base" in
  push-subtree) action=push ;;
  pull-subtree) action=pull ;;
  subtree)
    if test "${1+SET}" != SET
    then
      exit 1
    fi
    cmd="$1"
    shift
    case "$cmd" in
      push) action=push ;;
      pull) action=pull ;;
      *) exit 1 ;;
    esac
    ;;
  *) exit 1 ;;
esac
repos=$(cat repos)
toplevel="$(git rev-parse --show-toplevel)"
prefix=${PWD##$toplevel/}
cd "$toplevel"
case "$action" in
  push) git subtree push --prefix "$prefix" "$repos" main ;;
  pull) git subtree pull --prefix "$prefix" "$repos" --squash main ;;
esac
